FROM nginx:latest

# Remove the default configuration file
RUN rm /etc/nginx/ocnf.d/default.configuration

# Copy the custom configuration file into the container
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

# Conpy static json resources
COPY ../data/service-responces/user.json /usr/share/nginx/html/user.json